### ISSUE TITLE
JOSE reviews documentation evaluation

### ISSUE THREAD

**Issue by RobinHankin** [RobinHankin/schwarzschild#27]
Also, @IanHawke, thanks for kicking off the review. I'm not sure how to evaluate documentation and examples, as both are internal to R. It would be useful to have external examples to give the user a head start, but there are internal instructions for those who already installed the library.

(issue #14 refers)

**Comment by IanHawke** [comment]
It may be worth having a look at the documentation process for other R-based JOSE repos (there's only two that I can see at https://jose.theoj.org/papers/in/R).

Whilst they're a good place to start, we may want to think about the audience at which the libraries are aimed when thinking about the best documentation route. I would think that a repo with material for "staff" (who are assumed at least minimally competent in the language) would be somewhat different to one aimed at "learners" (where we can't make that assumption).

Finally, it's always worth cross-checking against the general criteria for JOSE - the documentation checklist is at https://openjournals.readthedocs.io/en/jose/review_checklist.html#documentation. For example, you've got a useful Statement of Need, but I'd be asking who the target audience is, and where this is made clear (I'd expect at least the paper and the README).

**Comment by RobinHankin** [comment]
Thanks for this @IanHawke, I've made a start on the review already and it's always good to have guidance.  I take your point about "staff" and "learners".

Can I clarify something?  the "Also, @IanHawke, thanks for kicking off the review..." above wasn't written  by me, it was copied from the comments of atrisovic.  I guess I am still getting used to the ins and outs of Github.    But I really really appreciate your guidance and advice.  Really.  Best wishes, Robin

**Comment by RobinHankin** [comment]
Tag 1.0-5 fixes these issues
